apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8sdemo-backend
  name: k8sdemo-backend
spec:
  ports:
    - nodePort: 31110
      port: 9110
      protocol: TCP
      targetPort: 9110
  selector:
    app: k8sdemo-backend
  type: NodePort
